name: flutter_user_app
description: A Flutter app demonstrating MVVM pattern with user data.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9 # 상태관리
  http: ^1.1.0 # API 통신

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true 